#!/usr/bin/env ruby
puts 'Loading script/rails'

APP_PATH = File.expand_path('../config/application', __dir__)
require File.expand_path('../config/boot', __dir__)

puts 'Loading rails/commands'
require 'rails/commands'
