# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rails', '3.2.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'awesome_print'
gem 'devise'
gem 'pg'
gem 'simple_form'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'bootstrap-sass', '~>2.0.0'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'haml-rails'
  gem 'sass-rails',   '~> 3.2.3'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :development, :test do
  gem 'capybara'
  gem 'capybara-firebug'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'ffaker'
  gem 'fuubar'
  gem 'rspec-rails'
  gem 'shoulda'

  gem 'hirb'
  gem 'wirble'
end
