source 'http://rubygems.org'

gem 'haml-rails'
gem 'jquery-rails'
gem 'pg'
gem 'rails', '3.1.3'
gem 'simple_form'

group :development, :test do
  gem 'capybara', '>= 1.1.2'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'rspec', '2.7'
  gem 'rspec-core', '2.7'
  gem 'rspec-expectations', '2.7'
  gem 'rspec-mocks', '2.7'
  gem 'rspec-rails', '2.7'
  gem 'spork'
end
