# frozen_string_literal: true

source 'http://rubygems.org'

gem 'coffee-script'
gem 'haml-rails'
gem 'jquery-rails'
gem 'pg'
gem 'rails', '3.1.3'
gem 'sass'
gem 'simple_form'
gem 'twitter-bootstrap-rails'

group :development, :test do
  gem 'capybara', '>= 1.1.2'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'rspec-rails', '2.7'
  gem 'shoulda-matchers'
  gem 'spork'
end
