source 'http://rubygems.org'

gem 'coffee-script'
gem 'haml-rails'
gem 'jquery-rails'
gem 'rails', '3.1.3'
gem 'sass'
gem 'simple_form'
gem 'twitter-bootstrap-rails'

gem 'bson_ext', '~> 1.5'
gem 'mongoid', '~> 2.4'

group :development, :test do
  gem 'capybara', '>= 1.1.2'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'rspec', '2.7'
  gem 'rspec-core', '2.7'
  gem 'rspec-expectations', '2.7'
  gem 'rspec-mocks', '2.7'
  gem 'rspec-rails', '2.7'
  gem 'spork'
end
