source 'https://rubygems.org'

gem 'haml-rails'
gem 'jquery-rails'
gem 'pg'
gem 'rails', '3.2.1'

group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'sass-rails',   '~> 3.2.3'
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
  gem 'awesome_print'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'fabrication'
  gem 'ffaker'
  gem 'rspec-rails'
  gem 'shoulda-matchers'
end
